
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  mustache:
    susffix: .html


